### ISSUE TITLE
HIDE_JOIN_MESSAGES does not account for new join / leave messages

### ISSUE THREAD

**Issue by SirNapkin1334** [builder-247/node-autotip#13]
I would make a PR but I just cannot find the piece of code that detects this. The config setting "HIDE_JOIN_MESSAGES" does not work, as the join messages format was changed, from `<playername> <left|joined>` to `<Guild|Friend> > <playername> <joined|left>.` Do note that it is now differently colored. Example of my chat getting spammed by it:
![image](https://user-images.githubusercontent.com/31591796/80851126-90fc4180-8bd4-11ea-9c53-9f32a41c06fe.png)
Should be a fairly simple fix, just replace the string that is used for detection.

**Comment by builder-247** [comment]
The related line is:
https://github.com/builder-247/node-autotip/blob/d9feab7782a701cd56f4232b4b07dca48ba851a0/index.js#L72

**Comment by SirNapkin1334** [comment]
Figures. It's the one JS file I didn't look at, and grep didn't seem to pick it up. I will create a pull request fixing this and removing Watchdog messages, which I will do in about 1.25 hours when the next watchdog message sends.

**Comment by builder-247** [comment]
Closed via #16
