### ISSUE TITLE
Never Reconnects!

### ISSUE THREAD

**Issue by Aidan-Lineberry** [builder-247/node-autotip#14]
All works well unless I log in from another location, (get kicked on node-at) and log out. The program will never reconnect.

Node-AT: v2.1.3
NodeJS: v10.19.0
NPM: v6.14.4
OS: Ubuntu 20.04 LTS

Terminal output: https://paste.ubuntu.com/p/qwGmJk7B56/

**Comment by SirNapkin1334** [comment]
For me, it does reconnect, however, it doesn't send me to limbo again and it does not continue tipping (or maybe it stops outputting?). My internet has been spotty lately, so I suspect it's connection to AT servers has been disrupted, and it never reconnects.
