### ISSUE TITLE
Getting blocked from using /tip

### ISSUE THREAD

**Issue by ItsNeverAlan** [builder-247/node-autotip#19]
Hypixel blocked me from using the /tip command for 5 minutes since the bot is spamming it , maybe add a detection to check for the message and pause the bot for 5 minutes if it shows up?

**Comment by builder-247** [comment]
Have you pulled the latest version from GitHub?

**Comment by ItsNeverAlan** [comment]
Yes , it's the latest build from 20 days ago. It rarely happens btw

**Comment by builder-247** [comment]
The latest commit should fix the root cause this issue.

**Comment by ItsNeverAlan** [comment]
Ok , you can close this issue now
