### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by 1kclouds** [builder-247/node-autotip#24]
I have a microsoft account, and it says my credentials are wrong. Im 100% sure its them. Why is it like that??
![image](https://user-images.githubusercontent.com/89359611/133844280-cbafe67b-62ca-4e7a-a7d1-f40105542f5c.png)

**Comment by builder-247** [comment]
Microsoft accounts aren't currently supported. You can try manually updating the mineflayer package.

**Comment by 1kclouds** [comment]
> Microsoft accounts aren't currently supported. You can try manually updating the mineflayer package.
I put my old mojang account (non-migrated I just don't wanna migrate) there and it still says invalid credentials. I tried username and email as the first, and the two passwords I use. Not working still

**Comment by builder-247** [comment]
Closed via https://github.com/builder-247/node-autotip/pull/27
