### ISSUE TITLE
Not receiving tips from other Autotip users

### ISSUE THREAD

**Issue by SylveonBottle** [builder-247/node-autotip#42]
My stats show `"tips_received":0`.

However, mere 30 seconds of joining the game on my forge client with Autotip, I received a tip from 2 other people.

**Comment by builder-247** [comment]
This is something done by the autotip backend, they probably now check for essential session or something. Nothing can be really done about it.

**Comment by SylveonBottle** [comment]
What are the expected losses for not being apart of autotip's node? Any estimate would be nice.

**Comment by builder-247** [comment]
> What are the expected losses for not being apart of autotip's node? Any estimate would be nice.

You can probably get a decent estimate by comparing few hours with the official client and node-at. Obviously the concurrent players affect as well. Karma wise node-at still beats the official client.

**Comment by SylveonBottle** [comment]
One could probably set up a minimal java client with auto-tip and some form of auto-multiplayer-connect at the lowest settings.
In which case, I wonder just how long minecraft can last with only 2-4gb of ram if it's just sitting in limbo with modded render distance of 1

**Comment by SylveonBottle** [comment]
Nevermind, looks like autotip is brken as well. Hypixel changed their system so you can only tip a gamemode once every hour it looks like.
![image](https://user-images.githubusercontent.com/17802843/233715355-869ee66c-8dbe-4b94-b36e-e56f161f02cc.png)
